[package]
name = "hyprkeymap"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"

[build-dependencies]
clap = { version = "4.5.38", features = ["derive"] }
clap_mangen = "0.2.26"
dirs = "6.0.0"
